config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root "routes#index"
	
	resources :routes
	resources :comments
	
	resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/route.rb
class Route < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :routes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  	end
  	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
	
	end
	
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
#    before_action :authenticate_user!


	def index
		@routes = Route.order('created_at DESC').page(params[:gage]).per(5)
	end
	
	def new
		@routes = Route.new
	end
	
	def create
		Route.create(route_params)
		redirect_to action: :index
	end
	
	def edit
		@route = Route.find(params[:id])
	
	end
	
	def update
		route = Route.find(params[:id])
		route.update(route_params)
		redirect_to action: :index
	end
	
	def destroy
		route = Route.find(params[:id])
		if route.user_id == current_user.id
			route.destroy
		end	
		redirect_to action: :index
	end
	
	
	private
	def route_params
		params.require(:route).permit(:title, :location, :map, :distance).merge(user_id: current_user.id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

	def new
	
	end
	
	def create
		User.create(user_params)
	
	end
	
	def destroy
		redirect_to root
	
	end
	
	def show
		@nickname = current_user.nickname
		@routes = Route.where(user_id: current_user.id).order('updated_at DESC')
	
	end
	
	
	private
	def user_params
		params.permit(:email, :nickname, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h3>＜コメントのページ＞</h3>
<hr>

<!-- ------------------	メニュー	------------------ -->
<table>
  <tr>
    <td><%= link_to '書き込む', new_route_path %></td>
    <td>　</td>
<% if user_signed_in? %>
    <td><%= link_to "ユーザページ", "/users/#{current_user.id}" %></td>
<% else %>
    <td>ユーザページ</td>
<% end %>
    <td>　</td>
<% unless user_signed_in? %>
    <td><%= link_to 'サインアップ', new_user_session_path %></td>
    <td>　</td>
<% end %>

<% if user_signed_in? %>
	<td>ログイン中</td>
	<% else %>
    <td><%= link_to 'ログイン', user_session_path %></td>
<% end %>

    <td>　</td>
    <td><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></td>
  </tr>
</table>

<hr>

<!-- ------------------	メニュー end	------------------ -->



<div id="result">ああああ</div>

<div id="map_canvas" style="width: 200px; height: 300px"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cybook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBs5SzjnpO0CBnZkjT3wlODSiF2_VqgjN4"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<script type="text/javascript">
      function initialize() {
        var mapDiv = document.getElementById("map_canvas");
        var mapCanvas = new google.maps.Map(mapDiv, 
        {
          center : new google.maps.LatLng(35.681382, 139.766084),
          zoom : 12,
          mapTypeId : google.maps.MapTypeId.ROADMAP
        });
      }

      google.maps.event.addDomListener(window, "load", initialize);
</script>

  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/routes/create.html.erb
<%= form_for(@routes, :url => {:action => 'create'}) do |f| %>
    <div class="field">
    <%= f.label :title %>
  <p><%= f.text_field :title %></p>
    <%= f.label :location %>
  <p><%= f.text_area :location, size: "60x12" %></p>
    <%= f.label :map %>
  <p><%= f.text_area :map, size: "60x12" %></p>
    <%= f.label :distance %>
  <p><%= f.text_area :distance, size: "60x12" %></p>
 <%= f.submit "書き込む" %>
<% end %>

app/views/routes/edit.html.erb
<%= form_for(@route) do |f| %>
    <div class="field">
    <%= f.label :title %>
  <p><%= f.text_field :title %></p>
    <%= f.label :location %>
  <p><%= f.text_area :location, size: "60x4" %></p>
    <%= f.label :map %>
  <p><%= f.text_area :map, size: "60x4" %></p>
    <%= f.label :distance %>
  <p><%= f.text_area :distance, size: "60x4" %></p>
 <%= f.submit "書き込む" %>
<% end %>

app/views/routes/index.html.erb
<h3>＜ルートブック＞</h3>
<hr>

<!-- ------------------	メニュー	------------------ -->
<table>
  <tr>
    <td><%= link_to '書き込む', new_route_path %></td>
    <td>　</td>
<% if user_signed_in? %>
    <td><%= link_to "ユーザページ", "/users/#{current_user.id}" %></td>
<% else %>
    <td>ユーザページ</td>
<% end %>
    <td>　</td>
<% unless user_signed_in? %>
    <td><%= link_to 'サインアップ', new_user_session_path %></td>
    <td>　</td>
<% end %>

<% if user_signed_in? %>
	<td>ログイン中</td>
	<% else %>
    <td><%= link_to 'ログイン', user_session_path %></td>
<% end %>

    <td>　</td>
    <td><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></td>
  </tr>
</table>

<hr>

<!-- ------------------	メニュー end	------------------ -->



<% @routes.each do |route| %>
	<p>タイトル：<%= route.title %></p>
	<p>地　　域：<%= route.location %></p>
	<p>ルート地図：<%= route.map %></p>
	<p>距　　離：<%= route.distance %> km</p>
	<p>ユーザ：<%= route.user.nickname %></p>
	<div id="map_canvas" style="width: 200px; height: 150px"></div>
	<hr>
<% end %>

<%= paginate @routes %>

<div id="result">ああああ</div>



<%= link_to 'コメント', comments_path %>

app/views/routes/new.html.erb
<%= form_for(@routes, :url => {:action => 'create'}) do |f| %>
    <div class="field">
    <%= f.label :title %>
  <p><%= f.text_field :title %></p>
    <%= f.label :location %>
  <p><%= f.text_area :location, size: "60x4" %></p>
    <%= f.label :map %>
  <p><%= f.text_area :map, size: "60x4" %></p>
    <%= f.label :distance %>
  <p><%= f.text_area :distance, size: "60x4" %></p>
 <%= f.submit "書き込む" %>
<% end %>

app/views/users/show.html.erb
<h4>＜ユーザ： <%= @nickname %>　のページ＞</h4>

<% if user_signed_in? %>
	<div><%= image_tag current_user.image, :size =>'70x90' %></div>
<% end %>

	<hr>

<!-- ------------------	メニュー	------------------ -->
<table>
  <tr>
    <td><%= link_to '書き込む', new_route_path %></td>
    <td>　</td>
    <td><%= link_to 'トップに戻る', root_path %></td>
    <td>　</td>
<% unless user_signed_in? %>
    <td><%= link_to 'サインアップ', new_user_session_path %></td>
    <td>　</td>
<% end %>

<% if user_signed_in? %>
	<td>ログイン中</td>
	<% else %>
    <td><%= link_to 'ログイン', user_session_path %></td>
<% end %>

    <td>　</td>
    <td><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></td>
  </tr>
</table>

<hr>

<!-- ------------------	メニュー end	------------------ -->



<% @routes.each do |route| %>
	<p>タイトル：<%= route.title %></p>
	<p>地　　域：<%= route.location %></p>
	<p>ルート地図：<%= route.map %></p>
	<p>距　　離：<%= route.distance %> km</p>
	<tr>
		<td><%= link_to "編集", "/routes/#{route.id}}/edit" %></td>
    	<td>　</td>
		<td><%= link_to "削除", "/routes/#{route.id}}", method: :delete %></td>
	</tr>
	<hr>

<% end %>

<p><%= link_to 'トップに戻る', root_path %></p>